services:
  - type: web
    name: spendwise-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
