services:
  - type: web
    name: spendwise-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_db.py && gunicorn run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
